PREFIX bf: <http://bibframe.org/vocab/>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lvont: <http://lexvo.org/ontology#>


# TODO:
# - numberOfPages values should be integer
# - datePublished sometimes has garbage e.g. copyright symbols and brackets e.g. "[1984]"
# - not everything should be typed schema:Book
# - add more detailed series types (e.g. BookSeries) when possible
# - classification codes should be added
# - publication events could be added
# - need to decide how to handle authority linking (people, organizations, places)

CONSTRUCT {
  ?inst a schema:Book, schema:CreativeWork ;
    schema:exampleOfWork ?work ;
    schema:name ?instTitleValue ;
    schema:description ?note ;
    schema:creator ?creator ;
    schema:exampleOfWork ?work ;
    schema:isbn ?isbn10val, ?isbn13val ;
    schema:datePublished ?providerDate ;
    schema:numberOfPages ?extent ;
    schema:publisher ?providerOrganization .
  ?providerOrganization a schema:Organization ;
    schema:name ?providerOrganizationLabel .
  ?creator a schema:Person ;
    schema:name ?creatorLabel .
  ?contributor a schema:Person ;
    schema:name ?contributorLabel .
  ?elec a schema:Book, schema:CreativeWork ;
    schema:exampleOfWork ?work ;
    schema:creator ?creator ;
    schema:url ?elecUri ;
    schema:name ?instTitleValue ;
    schema:bookFormat schema:EBook .
  ?work a schema:CreativeWork ;
    schema:workExample ?inst ;
    schema:translationOfWork ?origwork ;
    schema:isPartOf ?series ;
    schema:creator ?creator ;
    schema:contributor ?contributor ;
    schema:inLanguage ?languageCode ;
    schema:about ?subject, ?ysoSubject ;
    schema:name ?instTitleValue .
  ?origwork a schema:CreativeWork ;
    schema:workTranslation ?work ;
    schema:name ?origworkTitle ;
    schema:inLanguage ?origLanguageCode ;
    schema:author ?origworkCreator .
  ?origworkCreator a schema:Person ;
    schema:name ?origworkCreatorLabel .
  ?series a schema:CreativeWorkSeries, ?seriesType ;
    schema:hasPart ?work ;
    schema:name ?seriesTitleValue ;
    schema:issn ?seriesIssnValue .
}
WHERE {
  ?inst bf:instanceOf ?work .
  ?inst bf:instanceTitle ?instTitle .
  ?instTitle bf:titleValue ?instTitleValue .
  OPTIONAL {
    ?inst bf:isbn10 ?isbn10 .
    BIND(STRAFTER(STR(?isbn10), 'http://isbn.example.org/') AS ?isbn10val) 
  }
  OPTIONAL {
    ?inst bf:isbn13 ?isbn13 
      BIND(STRAFTER(STR(?isbn13), 'http://isbn.example.org/') AS ?isbn13val) 
  }
  OPTIONAL {
    ?inst bf:publication ?provider .
    OPTIONAL {
      ?provider bf:providerDate ?providerDate .
    }
    OPTIONAL {
      ?provider bf:providerName ?providerOrganization .
      ?providerOrganization bf:label ?providerOrganizationLabel .
    }
  }
  OPTIONAL {
    ?inst bf:extent ?extent .
  }
  OPTIONAL {
    ?inst bf:note ?note .
  }
  OPTIONAL {
    ?elec bf:instanceOf ?work .
    ?elec a bf:Electronic .
    ?elec bf:uri ?elecUri .
  }
  OPTIONAL {
    ?work bf:creator ?creator .
    ?creator bf:label ?creatorLabel .
  }
  OPTIONAL {
    ?work bf:contributor ?contributor .
    ?contributor bf:label ?contributorLabel .
  }
  OPTIONAL {
    ?work bf:translationOf ?origwork .
    ?origwork bf:title ?origworkTitle .
    ?origwork bf:creator ?origworkCreator .
    ?origworkCreator bf:label ?origworkCreatorLabel .
    FILTER(LANG(?origworkTitle) != 'x-bf-sort')
  }
  OPTIONAL {
    ?work bf:series ?series .
    ?series bf:title ?seriesTitle .
    BIND(REPLACE(?seriesTitle, ',[^,]+$', '') AS ?seriesTitleValue)
    OPTIONAL {
      ?series bf:issn ?seriesIssn .
      BIND(STRBEFORE(STRAFTER(STR(?seriesIssn), 'urn:issn:'),';') AS ?seriesIssnValue)
      BIND(schema:Periodical as ?seriesType)
    }
  }

  ?work bf:language ?language .
  FILTER (STRSTARTS(STR(?language), 'http://id.loc.gov/vocabulary/languages/'))
  BIND(STRAFTER(STR(?language), 'http://id.loc.gov/vocabulary/languages/') AS ?languageVal)
  OPTIONAL {
    GRAPH ?lexvoGraph {
      ?langent lvont:iso6392BCode ?languageVal .
      ?langent lvont:iso639P1Code ?iso6391code .
    }
  }
  BIND(IF(BOUND(?iso6391code), ?iso6391code, ?languageVal) AS ?languageCode)

  OPTIONAL {
    ?work bf:language ?origLanguage .
    ?origLanguage bf:resourcePart "original" .
    ?origLanguage bf:languageOfPartUri ?origLanguageUri .
    BIND(STRAFTER(STR(?origLanguageUri), 'http://id.loc.gov/vocabulary/languages/') as ?origLanguageVal)
    OPTIONAL {
      GRAPH ?lexvoGraph {
        ?origlangent lvont:iso6392BCode ?origLanguageVal .
        ?origlangent lvont:iso639P1Code ?origIso6391code .
      }
    }
    BIND(IF(BOUND(?origIso6391code), ?origIso6391code, ?origLanguageVal) AS ?origLanguageCode)
  }

  OPTIONAL {
    ?work bf:subject ?topic .
    ?topic bf:authorizedAccessPoint ?topicLabel .
    BIND(STRLANG(?topicLabel, 'fi') AS ?topicLabelFi)
    OPTIONAL {
      GRAPH ?ysaGraph { 
        ?ysac skos:prefLabel ?topicLabelFi .
        OPTIONAL { ?ysac skos:closeMatch ?ysoSubject }
      }
    }
    OPTIONAL {
      GRAPH ?ysaGraph { 
        ?ysac skos:altLabel ?topicLabelFi .
        OPTIONAL { ?ysac skos:closeMatch ?ysoSubject }
      }
    }
    BIND(IF(BOUND(?ysac), ?ysac, ?topicLabelFi) AS ?subject)
  }
}

